[tools]
aapt2 = "latest"
apk-editor = "latest"
apktool = "latest"
dex2jar = "latest"
gradle = "latest"
jadx = "latest"
java = "latest"
jq = "latest"
kotlin = "latest"
maven = "latest"
node = "latest"
python = "latest"
smali = "latest"
uber-apk-signer = "latest"
