# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{
  pkgs,
  python3Packages,
  fetchurl,
  fetchgit,
  fetchhg,
}:

{
  memoization = python3Packages.buildPythonPackage rec {
    pname = "memoization";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/53/e948a943e16423a87ced16e34ea7583c300e161a4c3e85d47d77d83830bf/memoization-0.4.0.tar.gz";
      sha256 = "0dd1712ksl1anjxvpdfcfb29s0mj2zncy403bq9mpx0f0v6ygrgx";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
}
