{ config, lib, pkgs, modulesPath, ... }:

{

    # Bootloader.
  boot = {
    kernelPackages = pkgs.linuxPackages_zen; 
    kernelModules = ["v4l2loopback"]; # This module allows you to create "virtual video devices". Normal (v4l2) applications will read these devices as if they were ordinary video devices, but the video will not be read from e.g. a capture card but instead it is generated by another application. This allows you for instance to apply some nifty video effects on your Skype video...
    
    kernelParams = [
    "amdgpu.runpm=0"
    # optionally also:
    # "amdgpu.dc=0"
  ];
    extraModulePackages = [
      config.boot.kernelPackages.v4l2loopback
      config.boot.kernelPackages.rtl8814au # Alpha AWUS wifi drivers 
    ];

    kernel.sysctl = {
      "vm.max_map_count" = 2147483642;
    };

    loader = {
      #systemd-boot.enable = true;        ?? # Whether to enable the systemd-boot (formerly gummiboot) EFI boot manager
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot";
      };

      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        useOSProber = true;
      };

    };

    tmp = {
      useTmpfs = true;
      tmpfsSize = "30%";
    };

    plymouth.enable = true; # Whether to enable Plymouth boot splash screen. providing a flicker-free graphical boot process.
  };
}